/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { type ParkingSpaces } from "@prisma/client";
import Link from "next/link";
function Card({listing}:{listing: ParkingSpaces}){
    return (
      <div className="h-30 max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        {/* <a href="#">
            <img className="rounded-t-lg" src="/docs/images/blog/image-1.jpg" alt="" />
        </a> */}
        <div className="p-5">
            <a href="#">
                <h5 className="mb-2 text-2xl font-bold tracking-tight
                 text-gray-900 dark:text-white">
                  {listing.parkingNumber}</h5>
            </a>
            <p className="h-20 mb-3 font-normal text-gray-700 dark:text-gray-400">
              {listing.status}</p>
  
            <Link href={`/listings/${listing.id}`} className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Reserve Parking
  
            </Link>
        </div>
    </div>
      )
    
  }
const ListingView: NextPage = () => {
  const router = useRouter();
  console.log(router.query.id)
  const listing = api.listing.get.useQuery(
    {
        listingIds: parseInt(router.query.id as string, 10),
    },
    {
      enabled: !!router.query.id,
    }
  );
  const listingItem = listing.data;

  if (!listingItem) {
    return null;
  }

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 bg-gray-800">
        <div className="container mx-auto flex flex-col gap-12">
        {listing?.data?.map((listing)=>(<Card key={listing.id} listing={listing}/>))}
        </div>
      </main>
    </>
  );
};

export default ListingView;