
import { type ParkingLocation, } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

function Card({listing}:{listing: ParkingLocation}){
  return (

    <div className="h-30 max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
      {/* <a href="#">
          <img className="rounded-t-lg" src="/docs/images/blog/image-1.jpg" alt="" />
      </a> */}
      <div className="p-5">
          <a href="#">
              <h5 className="mb-2 text-2xl font-bold tracking-tight
               text-gray-900 dark:text-white">
                {listing.name}</h5>
          </a>
          <p className="h-20 mb-3 font-normal text-gray-700 dark:text-gray-400">
            {listing.location}</p>

          <Link href={`/listings/${listing.id}`} className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Park Here

          </Link>
      </div>
  </div>
    )
  
}

type Card2Props = {
  name: string;
  location: string;
  link:string;
};

function Card2({ name, location, link }: Card2Props) {
  return (
    <div className="h-30 max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
      {/* <a href="#">
          <img className="rounded-t-lg" src="/docs/images/blog/image-1.jpg" alt="" />
      </a> */}
      <div className="p-5">
        <a href="#">
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            {name}
          </h5>
        </a>
        <p className="h-20 mb-3 font-normal text-gray-700 dark:text-gray-400">
          {location}
        </p>
        <Link
          href={`/${link}`}
          className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
        >
          Park Here
        </Link>
      </div>
    </div>
  );
}



const Home: NextPage = () => {
  

  const listings = api.listing.list.useQuery();
  return (
    <>
      <Head>
        <title>Parking Spaces</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white flex min-h-screen flex-col ">
        <h1 className="text-4xl mt-12 pl-4">Paking Lots</h1>
      <div className="container grid grid-row-4 items-center justify-center gap-12 px-4 py-16 ">
    {listings?.data?.map((listing)=>(<Card key={listing.id} listing={listing}/>))}

    <Card2 name={"CPU"} location={"Jaro"} link={"Jaro"} />
    <Card2 name={"Mcdonalds"} location={"Jalandoni"} link={"Jalandoni"} />
        </div>
      </main>
    </>
  );
};

export default Home;
